### ISSUE TITLE
Using touchstart event to emulate hover

### ISSUE THREAD

**Issue by dascritch** [dascritch/ondemiroir-audio-tag#37]

**Comment by dascritch** [comment]
something like ???

```css
.{{classname}} [title]::hover:after {
 display: block;
 position : absolute;
 top : -100%;
 content: attr(title);
 font-size:10px;
}
```
